config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

jaffle_shop:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "123"
      dbname: lesson15
      schema: dbt
  target: dev  